name: 'WissKI Grain, Yeast, and Water'
description: 'WissKI base environment with mandatory modules.'
type: 'Site'

install:
  - inline_entity_form
  - wisski

config:
  #strict: false # this is not implemented in D11
  import:
    inline_entity_form: "*"
    wisski: "*"
