name: 'WissKI Grain, Yeast, and Water'
description: 'WissKI base environment with mandatory modules.'
type: 'Site'

install:
  - inline_entity_form
  - wisski

config:
  import:
    inline_entity_form: "*"
    wisski: "*"
